apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-pvc
  namespace: dark-notes
spec:
  storageClassName: loki-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
