backend:
  replicaCount: 3

  image:
    repository: mudocker67/darknotes-backend
    tag: latest
    pullPolicy: Always

  service:
    type: ClusterIP
    port: 80
    targetPort: 5000

  resources:
    requests:
      cpu: "250m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

frontend:
  replicaCount: 3

  image:
    repository: mudocker67/darknotes-frontend
    tag: latest
    pullPolicy: Always

  service:
    type: ClusterIP
    port: 80
    targetPort: 80

  resources:
    requests:
      cpu: "250m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

config:
  nodeEnv: "production"
  port: "5000"
  apiPrefix: "/api"

secret:
  supabaseUrl: ""
  supabaseServiceRoleKey: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

ingress:
  enabled: true
  className: nginx

  annotations: {}# ==========================================
# Monitoring Stack Configs (Loki, Promtail, Grafana)
# ==========================================
loki:
  auth_enabled: false
  deploymentMode: SingleBinary

promtail:
  config:
    clients:
      # Automatically targets the Loki service created by your deployment release name
      - url: http://{{ .Release.Name }}-loki-gateway/loki/api/v1/push

grafana:
  enabled: true
  adminPassword: "admin" # Default dashboard password for testing
  persistence:
    enabled: false # Keeps it lightweight using temporary cluster storage
