backend:
  replicaCount: 3

  image:
    repository: mudocker67/darknotes-backend
    tag: latest
    pullPolicy: Always

  service:
    type: ClusterIP
    port: 80
    targetPort: 5000

  resources:
    requests:
      cpu: "250m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

frontend:
  replicaCount: 3

  image:
    repository: mudocker67/darknotes-frontend
    tag: latest
    pullPolicy: Always

  service:
    type: ClusterIP
    port: 80
    targetPort: 80

  resources:
    requests:
      cpu: "250m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

config:
  nodeEnv: "production"
  port: "5000"
  apiPrefix: "/api"

secret:
  supabaseUrl: ""
  supabaseServiceRoleKey: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

ingress:
  enabled: true
  className: nginx

  annotations: {}
# Monitoring Stack Configurations
# -----------------------------
# Loki Distributed
# -----------------------------
loki-distributed:
  enabled: true

  loki:
    auth_enabled: false

  ingester:
    persistence:
      enabled: true
      storageClass: loki-storage
      accessModes:
        - ReadWriteOnce
      size: 20Gi

# -----------------------------
# Promtail
# -----------------------------
promtail:
  enabled: true

  config:
    clients:
      - url: http://{{ .Release.Name }}-loki-distributed-gateway/loki/api/v1/push

# -----------------------------
# Grafana
# -----------------------------
grafana:
  enabled: true

  datasources:
    datasources.yaml:
      apiVersion: 1

      datasources:
        - name: Loki
          type: loki
          access: proxy
          url: http://{{ .Release.Name }}-loki-distributed-gateway
          jsonData:
            maxLines: 1000
