apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "darknotes.fullname" . }}-frontend
  labels:
    app: frontend
    {{- include "darknotes.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.frontend.replicaCount }}

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      serviceAccountName: {{ include "darknotes.serviceAccountName" . }}

      containers:
        - name: frontend

          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.frontend.service.targetPort }}

          resources:
            requests:
              cpu: {{ .Values.frontend.resources.requests.cpu | quote }}
              memory: {{ .Values.frontend.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.frontend.resources.limits.cpu | quote }}
              memory: {{ .Values.frontend.resources.limits.memory | quote }}

          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.service.targetPort }}
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.service.targetPort }}
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3