apiVersion: v1
kind: Service
metadata:
  name: {{ include "darknotes.fullname" . }}-frontend
  labels:
    app: frontend
    {{- include "darknotes.labels" . | nindent 4 }}

spec:
  type: {{ .Values.frontend.service.type }}

  selector:
    app: frontend

  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}