apiVersion: v1
kind: Secret
metadata:
  name: {{ include "darknotes.fullname" . }}-secret
  labels:
    {{- include "darknotes.labels" . | nindent 4 }}

type: Opaque

stringData:
  SUPABASE_URL: {{ .Values.secret.supabaseUrl | quote }}
  SUPABASE_SERVICE_ROLE_KEY: {{ .Values.secret.supabaseServiceRoleKey | quote }}